---
title: "Project 2 Description"
date: "`r Sys.Date()`"
output: html_document
---

## Overview

This document contains instructions on Project 2 for STA 207 in Winter 2021. This document is made with `R markdown`. The `rmd` file to generate this document is available on the course website. 

## Background

The National Highway Traffic Safety Administration reported that there are 36,560 highway fatalities across US in 2018 ([link](https://www.nhtsa.gov/press-releases/roadway-fatalities-2018-fars)). 
Alarmed by the high traffic fatalities, you wanted to use your knowledge and skills in statistics to explore measures that can potentially reduce the traffic fatalities. 

You found out that traffic fatalities data for 48 US states from 1982 to 1988 are available, and well-cleaned, in an `R` package `AER`. You can see more description of the data set from the help file of the `Fatalities` dataset (e.g., using `?Fatalities`).

You want to analyze this dataset to see if there are any of the variables that **caused** the reduction or increase of traffic fatalities.

**<span style="color:red"> Note that the ultimate goal is to make suggestions to policymakers to take certain measures.</span>**

* The beer tax is the tax on a case of beer, which is an available measure of state alcohol taxes more generally. 

* The drinking age variable is a factor indicating whether the legal drinking age is 18, 19, or 20. 

* The two binary punishment variables describe the state's minimum sentencing requirements for an initial drunk driving conviction.

* Total vehicle miles traveled annually by state was obtained from the Department of Transportation. 

* Personal income was obtained from the US Bureau of Economic Analysis

* The unemployment rate was obtained from the US Bureau of Labor Statistics



## Suggested outline 


The following list provides one potential structure of the data analysis report. We will assume that the variable of interest is the indicator for having a mandatory jail sentence. You can pick other variables of interest to form your primary question of interest. 


1. Introduce the data set and the questions of interest.

2. Review the background of this data set. 
<span style='color:red'> Take a look at the help file for the `Fatalities` dataset.(e.g., using `?Fatalities`). </span>

3. Explore this dataset and generate summary statistics that you find informative, and explain your findings.  In particular,
    a. visualize the changes of numbers of vehicle fatalities `fatal` across years,
    b. and investigate the relationship between number of vehicle fatalities with the selected variables of interest. 


4.  Propose an appropriate model to answer the questions of interest. 
    a. Explain your notation. 
    b. State assumptions for your model. 
    c. Explain why your model is appropriate for this task. 
  
  

5.  Fit the proposed model in (4) and explain your results. 

6.  Discuss causal interpretation of the proposed models. There are two options here. 
    a. You may want to think about the causal interpretation before determining an appropriate model. You would need to search for some references. Some key words include longitudinal data, time-series data, propensity score, matching, instrument variable,  observational study, etc. 
    b. You can also discuss why your model (or this data set) cannot answer the question on causality. 



6.  Conduct model diagnostics and/or sensitivity analysis. 

7. Conclude your analysis with an discussion of your findings and caveats of your approach. <span style='color:red'> You may use additional data or studies to strengthen your argument here. </span>
